name: Deploy Flutter Web to Firebase

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'

      - run: flutter pub get
        working-directory: ./ngo_connect

      - run: flutter build web
        working-directory: ./ngo_connect

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_NGO_CONNECT_6DDEE }}
          channelId: live
          projectId: ngo-connect-6ddee
          entryPoint: ./ngo_connect
